const GET_TODO_LIST = 'GET_TODO_LIST',
      SET_TODO_LIST = 'SET_TODO_LIST',
      GET_POST_DETAIL = 'GET_POST_DETAIL',
      SET_POST_DETAIL = 'SET_POST_DETAIL'

      export{GET_POST_DETAIL,GET_TODO_LIST,SET_POST_DETAIL,SET_TODO_LIST}